{ config, pkgs, ... }:

{
  home.packages = with pkgs; [
    jira-cli-go # Jira CLI tool for work
  ];

  # Jira CLI configuration
  home.file.".config/.jira/.config.yml".text = ''
    # This file will be generated by 'jira init' command
    # The API token is loaded from environment variable JIRA_API_TOKEN
  '';
}